### ISSUE TITLE
Cross publish to npm?

### ISSUE THREAD

**Issue by Adammatthiesen** [oatmealproblem/shiki-colorized-brackets#1]
Hi, I am extremely interested in using this, but am not able to rely on the JSR package registry due to CI restrictions preventing me from keeping a modified `.npmrc` and was hoping that you'd be willing to cross post this onto the main NPM registry?  This would prevent me (and potentially others) from having to copy paste your code into my own repo.

**Comment by oatmealproblem** [comment]
Hi, the Shiki maintaining have expressed interest in adopting this as official plugin within the Shiki monorepo. If that happens, then it'll be published to npm through them. I just need to actually create the draft PR for that 😅

If they end up deciding not to adopt this, I'll look into publishing this existing package to npm

**Comment by oatmealproblem** [comment]
In the meantime, rather than using .npmrc, could you use `npm config set @jsr:registry=https://npm.jsr.io` somewhere in your CI to configure the JSR registry?

**Comment by Adammatthiesen** [comment]
Closing as I see shiki has just released it, Thanks for your great work!
